stages:
  - build

variables:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "2.0.0"

before_script:
  - flutter --version

cache:
  paths:
    - .pub-cache
    - build

build:
  stage: build
  script:
    - flutter pub get
    - flutter build apk




